version: 0.2

env:
  variables:
    NODE_ENV: production
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run heroku-postbuild
  build:
    commands:
      - nohup npm run start:babel &
      - sleep 3
      - npm run test
